openapi: 3.1.0
info:
  title: Google Search API
  version: 1.0.0
paths:
  /google:
    post:
      operationId: googleSearch
      summary: Google search
      description: |
        Perform a Google search and return the results.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - query
              properties:
                query:
                  type: string
                  description: The search query.
