openapi: 3.1.0
info:
  title: System Tool
  version: "v1"
paths:
  /system/info:
    get:
      operationId: getSystemInfo
      summary: Get System Information
      description: >
        System details such as username, permissions, os, cpu, memory, disk, terminal, clis, timezone, and time.
        This is the system environment that you are pair programming with the user on.
