openapi: 3.1.0
info:
  title: System Tool
  version: "v1"
paths:
  /system/info:
    get:
      operationId: getSystemInfo
      summary: Get System Information
      description: >
        Fetches various system details such as system architecture, platform, and versions of various tools like Git, Node.js, and Yarn.
  /system/location:
    get:
      operationId: getSystemLocation
      summary: Get System Location
      description: >
        Fetches the physical location of the user's device using the IP address.
