openapi: 3.1.0
info:
  title: Pair Programmer
  description: |
    Enables ChatGPT to pair program with the user on the user's own computer.
    This plugin run a local server giving ChatGPT the same access to the system that the user has.
    This plugin gives ChatGPT the ability execute terminal commands, browser the internet, run google searches, and more.
  version: "v1"
servers:
  - url: http://localhost:5004
# Paths are aggregated from tools/*/openapi.yaml
paths: {}
