openapi: 3.0.0
info:
  title: Webpage Open API
  version: 1.0.0
paths:
  /webpage/open:
    post:
      summary: Open a webpage using a provided URL.
      description: |
        Replaces the current webpage.
        Returns the readable text of the webpage.
      operationId: openWebpage
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                url:
                  type: string
                  format: uri
                  description: The URL of the webpage to open
                  example: https://example.com
  /webpage/close:
    post:
      summary: Close the currently open webpage
      operationId: closeWebpage

  /webpage/dom:
    get:
      summary: Read the Document Object Model (DOM) of the currently open webpage
      operationId: getWebpageDom

  /webpage/console:
    get:
      summary: Read the console logs of the currently open webpage
      operationId: getWebpageConsole

    delete:
      summary: Clear the console logs of the currently open webpage
      operationId: clearWebpageConsole

  /webpage/read:
    get:
      summary: Get a human readable version of the currently open webpge
      operationId: readWebpage
